### ISSUE TITLE
Add throwing an exception here

### ISSUE THREAD

**Issue by Kuyantsev-VP** [skhayrulin/x_engine#7]
If there were some problems during compiling the kernel source (we fall into the initialize_ocl in line 37), no ocl_solvers would be created, but execution would be continued. As a result, we would fall into make_partition and get division by zero in line 90 (in sph_model.hpp).
https://github.com/skhayrulin/x_engine/blob/62e8a74749a55e806beb60ca0939c1c7c64c33e5/inc/solver_container.hpp#L41

**Comment by skhayrulin** [comment]
Good catch I've fixed it in last commit
