### ISSUE TITLE
Should variable size_t end  be minus 1 ?

### ISSUE THREAD

**Issue by Kuyantsev-VP** [skhayrulin/x_engine#8]
May be this line should be like this: 
`partitions.push_back(partition{0, static_cast<size_t>(size() - 1)});`
?

If we have one device and we are trying to get last the last element in partition, it's desirable to write
`model->get_particles().at(p.end);`
which results in seg fault. 
May be I'm wrong?

https://github.com/skhayrulin/x_engine/blob/62e8a74749a55e806beb60ca0939c1c7c64c33e5/inc/sph_model.hpp#L87

**Comment by skhayrulin** [comment]
Ok got it
