### ISSUE TITLE
swap these lines: size_t cell_id;  size_t type_;

### ISSUE THREAD

**Issue by Kuyantsev-VP** [skhayrulin/x_engine#9]
https://github.com/skhayrulin/x_engine/blob/10b933e51ca2d3decda37aa342289be92f336f3d/cl_code/sph_cl_code.cl#L64

In the structure particle (in particle.h) the sequence of feilds is:
```
container pos;
container vel;
size_t type;
size_t cell_id;
size_t get_dim() const { return dim; }
T density;
T pressure;
```
In the structure particle_f (and also in particle_d) the sequence of feilds is:
```
float4 pos;
float4 vel;
size_t cell_id;
size_t type_;
float density;
float pressure;
```

As you can see, the feilds cell_id and type are written in a different order. That is the reason of data consistency problem.

**Comment by skhayrulin** [comment]
Fixed in last commit
